In [ ]:
#No70(単語ベクトルの和による特徴量)
import string
import torch
import pickle
import pandas as pd

# 前処理関数
def transform_w2v(text):
  # 前処理( !"#$%&'()*+,-./:;<=>?@[\]^_`{|}の除去)
    table = str.maketrans(string.punctuation, " " * len(string.punctuation))
  # 記号をスペースに置換し、スペースで分割
    words = text.translate(table).split()
  #wordがmodelにあるなら、wordをベクトル化して、リストに入れる(リスト内包表記)
    vec = [model[word] for word in words if word in model]
  # 特徴ベクトルを返す
  #tensor型はGPUの使用ができ、勾配情報(パラメータの更新に役立つ)を持っている
    return torch.from_numpy(sum(vec) / len(vec))


# モデルと学習，検証，評価データの読み込み(No50とNo60の利用)
model = pickle.load(open("/content/drive/MyDrive/GoogleNews-vectors.pkl", "rb"))
train = pd.read_csv("/content/drive/MyDrive/train.txt", sep="\t")
valid = pd.read_csv("/content/drive/MyDrive/valid.txt", sep="\t")
test = pd.read_csv("/content/drive/MyDrive/test.txt", sep="\t")

# 特徴ベクトルの作成(textを引数として、関数を呼び出し、返り値を連結していく)
X_train = torch.stack([transform_w2v(text) for text in train["TITLE"]])
X_valid = torch.stack([transform_w2v(text) for text in valid["TITLE"]])
X_test = torch.stack([transform_w2v(text) for text in test["TITLE"]])

# 形状の確認(次元の確認はdim,形状の確認はsizeを利用するとよい)
print(X_train.size())
print(X_train)

# ラベルベクトルの作成
category_dict = {"b": 0, "t": 1, "e": 2, "m": 3}
#lambdaの処理をmap関数によって繰り返し、値を入手する
y_train = torch.tensor(train["CATEGORY"].map(lambda x: category_dict[x]).values)
y_valid = torch.tensor(valid["CATEGORY"].map(lambda x: category_dict[x]).values)
y_test = torch.tensor(test["CATEGORY"].map(lambda x: category_dict[x]).values)

# 形状の確認
print(y_train.size())
print(y_train)

# 保存
torch.save(X_train, "X_train.pt")
torch.save(X_valid, "X_valid.pt")
torch.save(X_test, "X_test.pt")
torch.save(y_train, "y_train.pt")
torch.save(y_valid, "y_valid.pt")
torch.save(y_test, "y_test.pt")

'''
torch.Size([10672, 300])
tensor([[ 0.0063, -0.0099, -0.0265,  ...,  0.0352,  0.0331, -0.0137],
        [ 0.0280,  0.0331, -0.0769,  ..., -0.0445,  0.0516, -0.0313],
        [-0.0178,  0.0877, -0.1068,  ...,  0.0885,  0.1208, -0.0166],
        ...,
        [-0.0419,  0.0382, -0.2469,  ..., -0.0598, -0.0339,  0.1007],
        [ 0.0624,  0.0094,  0.0034,  ...,  0.0226,  0.0534, -0.1029],
        [-0.0191,  0.0342, -0.0186,  ...,  0.0232,  0.0922,  0.0722]])
torch.Size([10672])
tensor([0, 2, 0,  ..., 2, 0, 0])
'''

torch.Size([10672, 300])
tensor([[ 0.0063, -0.0099, -0.0265,  ...,  0.0352,  0.0331, -0.0137],
        [ 0.0280,  0.0331, -0.0769,  ..., -0.0445,  0.0516, -0.0313],
        [-0.0178,  0.0877, -0.1068,  ...,  0.0885,  0.1208, -0.0166],
        ...,
        [-0.0419,  0.0382, -0.2469,  ..., -0.0598, -0.0339,  0.1007],
        [ 0.0624,  0.0094,  0.0034,  ...,  0.0226,  0.0534, -0.1029],
        [-0.0191,  0.0342, -0.0186,  ...,  0.0232,  0.0922,  0.0722]])
torch.Size([10672])
tensor([0, 2, 0,  ..., 2, 0, 0])
