In [1]:
#作成したテンソルを読み込み
import torch
X_train = torch.load('/content/drive/MyDrive/Colab Notebooks/chapter08/X_train.pt')
X_test = torch.load('/content/drive/MyDrive/Colab Notebooks/chapter08/X_test.pt')
X_valid = torch.load('/content/drive/MyDrive/Colab Notebooks/chapter08/X_valid.pt')
Y_train = torch.load('/content/drive/MyDrive/Colab Notebooks/chapter08/Y_train.pt')
Y_test = torch.load('/content/drive/MyDrive/Colab Notebooks/chapter08/Y_test.pt')
Y_valid = torch.load('/content/drive/MyDrive/Colab Notebooks/chapter08/Y_valid.pt')

In [2]:
# モデルの構築(nnはニューラルネットワーク)
from torch import nn

class SLNet(nn.Module):
    def __init__(self, input_size, output_size):
        super().__init__()
        self.fc = nn.Linear(input_size, output_size) #全結合層の作成

    def forward(self, x):
        logits = self.fc(x)                          #フォワードパスの作成
        return logits

#入力300,出力4のサイズでインスタンスを作成
model = SLNet(300, 4)
print(model)

SLNet(
  (fc): Linear(in_features=300, out_features=4, bias=True)
)


In [3]:
#事例1についてのみの検証
logits = model(X_train[0])
y_hat_1 = nn.Softmax(dim=-1)(logits)   #dim=1によって行単位の処理
print(logits)
print(y_hat_1)

tensor([ 0.1009,  0.0172, -0.0042,  0.0302], grad_fn=<ViewBackward0>)
tensor([0.2666, 0.2452, 0.2399, 0.2483], grad_fn=<SoftmaxBackward0>)


In [4]:
#全事例に対して検証
logits = model(X_train[:4])
Y_hat = nn.Softmax(dim=1)(logits)
print(logits)
print(Y_hat)

tensor([[ 0.1009,  0.0172, -0.0042,  0.0302],
        [ 0.0924, -0.0700, -0.0909,  0.0518],
        [ 0.0367,  0.0248, -0.0938, -0.0354],
        [ 0.0425, -0.0163, -0.0451,  0.0053]], grad_fn=<AddmmBackward0>)
tensor([[0.2666, 0.2452, 0.2399, 0.2483],
        [0.2745, 0.2334, 0.2285, 0.2636],
        [0.2634, 0.2603, 0.2312, 0.2451],
        [0.2616, 0.2467, 0.2397, 0.2520]], grad_fn=<SoftmaxBackward0>)
